import {
  cancel,
  intro,
  isCancel,
  outro,
  password,
  select,
  tasks,
  text,
} from "@clack/prompts";
import fs from "node:fs";
import path from "node:path";
import child_process from "node:child_process";
import { promisify } from "node:util";

const cwd = process.cwd();
const packagePath = path.resolve(cwd, "..");

const execAsync = promisify(child_process.exec);

const getOrQuit = async <T>(prompt: Promise<T | symbol>): Promise<T> => {
  const value = await prompt;
  if (isCancel(value)) {
    cancel("Setup terminated.");
    process.exit(0);
  }

  return value;
};

const generateSecrets = async () => {
  const { stdout: secrets } = await execAsync(
    "pnpm --silent --workspace-root backend generate:secrets"
  );

  return secrets;
};

const generateKcmsEnv = (
  env: {
    adminUsername: string;
    adminPassword: string;
    cookieTokenKey: string;
    cookieMaxAge: number;
  },
  secrets: string
) => {
  const envPath = path.join(packagePath, "kcms/.env");
  const envContent = `KCMS_ADMIN_USERNAME=${env.adminUsername}
KCMS_ADMIN_PASSWORD=${env.adminPassword}
KCMS_COOKIE_TOKEN_KEY=${env.cookieTokenKey}
KCMS_COOKIE_MAX_AGE=${env.cookieMaxAge}

# generated by generate:secrets
${secrets}`;

  fs.writeFileSync(envPath, envContent);
};

const main = async () => {
  intro("Initial setup kcmsx");

  const adminUsername = await getOrQuit(
    text({
      message: "Tell us the admin username to use.",
      validate(value) {
        if (value.length == 0) return "The admin username cannot be empty.";
      },
    })
  );

  const adminPassword = await getOrQuit(
    password({
      message: "Tell us the admin password to use.",
      validate(value) {
        if (value.length == 0) return "The admin password cannot be empty.";
      },
    })
  );

  const cookieTokenKey = await getOrQuit(
    text({
      message: "What do you want the cookie token key to be?",
      initialValue: "kcms-token",
      validate(value) {
        if (value.length == 0) return "The cookie token key cannot be empty.";
      },
    })
  );

  const cookieMaxAge = await getOrQuit(
    select({
      message: "What do you want the cookie max age to be?",
      options: [
        { label: "10 minutes", value: 600 },
        { label: "30 minutes", value: 1800 },
        { label: "1 hour", value: 3600 },
        { label: "12 hours", value: 43200 },
        { label: "1 day", value: 86400, hint: "recommended" },
        { label: "30 days", value: 2592000 },
      ],
      initialValue: 86400,
    })
  );

  await tasks([
    {
      title: "Generating environment files...",
      task: async () => {
        const secrets = await generateSecrets();

        generateKcmsEnv(
          {
            adminUsername,
            adminPassword,
            cookieTokenKey,
            cookieMaxAge,
          },
          secrets
        );
        return "Environment files generated!";
      },
    },
  ]);

  outro("Done!");
};

main();
