name: CD for Fork

on:
  pull_request_target: # must read https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
  workflow_dispatch:
    inputs:
      cloudflare_api_token:
        description: Cloudflare API Token
        required: true
      cloudflare_account_id:
        description: Cloudflare Account Id
        required: true

permissions:
  contents: read
  pull-requests: write
  deployments: write

env:
  PROJECT_NAME: kcmsx

jobs:
  preview_for_fork:
    environment: Preview for Fork # require review to run
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    name: Preview Deploy for Fork
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/kcmsf

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - run: npm install -g --force corepack
      - run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build --mode staging

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN || inputs.cloudflare_api_token }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID || inputs.cloudflare_account_id }}
          command: pages deploy packages/kcmsf/dist --project-name=${{ env.PROJECT_NAME }}
